### ISSUE TITLE
Run on Bluemix - steps

### ISSUE THREAD

**Issue by vegas3416** [watsonwork/watsonwork-java-starter#2]
Prior to step 4 there should be a step that notates that you need to add the path for Bluemix to the Environment variables.

**Comment by ghost** [comment]
Thanks for reporting this. I believe this to only be a problem on windows, as macos and linux install to /usr/local/bin. I'll verify this on a windows vm soon when I can get somewhere with a better internet connection. Do you know if there was a similar problem when installing cf on windows?

**Comment by ghost** [comment]
I updated the doc, odd that cf adds itself to the path on windows but bluemix doesn't.

**Comment by vegas3416** [comment]
I didnt run into any issues with installing cf but will reattempt everything tonight and follow up
