### ISSUE TITLE
Could not find or load main class _WATSONWORK_JAVA_STARTER_BLUEMIX_OPTS

### ISSUE THREAD

**Issue by gitjps** [watsonwork/watsonwork-java-starter#6]
Deploying to Bluemix resulted in this error message.

**Comment by ghost** [comment]
Hi, did you run `gradlew clean build` before pushing?

**Comment by gitjps** [comment]
I think I did. I tried it today again and it worked. The only thing I don't understand is why the app does not link to the availability service automatically, which exists. Installation aborted:

OK
FAILED
Could not find service availability-monitoring-auto to bind to myapp

**Comment by ghost** [comment]
Sorry I wouldn't know anything about that, as far as I know that should automatically attach to any working app. The error looks like the service isn't actually available, so all I could say is be sure it's there. Thanks for reporting this issue, I'll close it now.
